volumes:
  prometheus_data: {}
  grafana_data: {}
  alerta_db: {}

networks:
  story-monitoring:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
       - type: volume
         source: prometheus_data
         target: /prometheus
       - type: bind
         source: ./prometheus
         target: /etc/prometheus
         read_only: true 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - story-monitoring
    restart: always

  # default login credentials: admin/admin
  grafana:
    image: grafana/grafana:latest
    env_file: ./grafana/grafana.conf
    container_name: grafana
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 9999:3000
    networks:
      - story-monitoring
    restart: always

  alerta_db:
    image: postgres:11
    container_name: alerta_db
    networks:
     - story-monitoring
    volumes:
      - type: volume
        source: alerta_db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: cosmos_monitoring
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    hostname: 'alerta_db'
    restart: always

  alerta:
    image: alerta/alerta-web:latest
    container_name: alerta
    networks:
     - story-monitoring
    ports:
       - 8083:8083
    depends_on:
      - alerta_db
    volumes:
      - type: bind
        source: ./alerta/alertad.conf
        target: /app/alertad.conf
        read_only: true
    environment:
      - DATABASE_URL=postgres://postgres:postgres@alerta_db:5432/monitoring
      - PLUGINS=reject,blackout
    hostname: 'alerta'
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    networks:
      - story-monitoring
    ports:
      - 9093:9093
    volumes:
      - type: bind
        source: ./prometheus/alert_manager
        target: /etc/alertmanager
        read_only: true
    command: [
      '--config.file=/etc/alertmanager/alertmanager.yml',
      '--log.level=debug',
    ]
    hostname: 'alertmanager'
    restart: always
