global:
  resolve_timeout: 1m

templates: 
- 'templates/*.tmpl'

route:
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        message: '{{ template "custom.alert.notification" . }}'  # Use your custom template here
        bot_token: 'YOUR_TELEGRAM_BOT_TOKEN'  # Put your telegram bot token here
        chat_id: 'YOUR_TELEGRAM_USER_ID'      # Put your telegram user id here
