{
 "title": "Namada Node Dashboard",
 "description": "This dashboard provides a comprehensive view of key metrics from Namada Protocol node. It offers insights into node performance, health and activity.",
 "tags": [
  "namada_tm",
  "geth"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(namada_tm_p2p_peers,instance)"
    }
   },
   {
    "name": "chain_id",
    "query": {
     "query": "label_values(namada_tm_p2p_peers,chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <br>\n    <img src=\"https://services.kjnodes.com/assets/images/logos/namada.png\"><br><br>\n    <h1>Namada Node Dashboard</h1>\n    <h5>⚡️ Powered by <a href=\"https://kjnodes.com\">kjnodes</a></h5>\n</div>"
   }
  },
  { "title": "kjnodes Namada Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/namada/\" target=\"_blank\">Namada Services</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/namada/installation/\" target=\"_blank\">Node Installation</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/namada/upgrade/\" target=\"_blank\">Node Upgrade</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/namada/state-sync/\" target=\"_blank\">State-Sync</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/namada/snapshot/\" target=\"_blank\">Snapshot</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/namada/useful-commands/\" target=\"_blank\">Useful Commands</a></h1>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h1><a href=\"https://services.kjnodes.com/testnet/namada/public-rpc/\" target=\"_blank\">RPC Scanner</a></h1>\r\n</div>"
   }
  },
  { "title": "Namada Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "# Cometbft Node Metrics\n\n*Metrics collected from a Namada Cometbft Prometheus endpoint.*\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>System</h2>\r\n</div>"
   }
  },
  {
   "title": "Service Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\", job=\"cometbft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_block_syncing{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_latest_block_height{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "namada_tm_consensus_latest_block_height{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\", job=\"cometbft\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\", job=\"cometbft\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\", job=\"cometbft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\", job=\"cometbft\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Network</h2>\r\n</div>"
   }
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_p2p_peers{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "namada_tm_p2p_peers{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(namada_tm_p2p_peer_receive_bytes_total{instance=\"$instance\", chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum(rate(namada_tm_p2p_peer_send_bytes_total{instance=\"$instance\", chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Blockchain</h2>\r\n</div>"
   }
  },
  {
   "title": "Block time",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 / round(increase(namada_tm_consensus_height{instance=\"$instance\", chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(namada_tm_consensus_height{instance=\"$instance\", chain_id=\"$chain_id\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(namada_tm_consensus_height{instance=\"$instance\", chain_id=\"$chain_id\"}[1m])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_block_size_bytes{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namada_tm_consensus_block_size_bytes{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Consensus Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_height{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_validators{instance=\"$instance\", chain_id=\"$chain_id\"} - namada_tm_consensus_missing_validators{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_missing_validators{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmed Tx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_total_txs{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_mempool_size_bytes{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namada_tm_mempool_size_bytes{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Online: bonded tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_validators_power{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline: bonded tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_missing_validators_power{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline: Voting Power %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_consensus_missing_validators_power{instance=\"$instance\", chain_id=\"$chain_id\"} / namada_tm_consensus_validators_power{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unconfirmed Tx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_tm_mempool_size{instance=\"$instance\", chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}